---
# tasks file for roles/service_deploy
- name: Install dependencies
  dnf:
    name:
      - python3
      - python3-pip
    state: present

- name: Install prometheus-client
  pip:
    name: prometheus-client
    executable: pip3

- name: Create application directory
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: 0755
    owner: appuser
    group: appuser

- name: Deploy application code
  copy:
    src: server.py
    dest: "{{ app_dir }}/server.py"
    mode: 0755
    owner: appuser
    group: appuser

- name: Configure firewall
  firewalld:
    port: "{{ app_port }}/tcp"
    permanent: yes
    state: enabled
  notify: Reload firewall

- name: Deploy systemd service
  template:
    src: metrics.service.j2
    dest: /etc/systemd/system/metrics.service
    mode: 0644
    owner: root
    group: root
  notify:
    - Reload systemd
    - Restart metrics service

- name: Ensure service is running
  systemd:
    name: metrics
    state: started
    enabled: yes
    daemon_reload: yes