services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.part5
  nginx:
    image: nginx
    depends_on:
      - webapp
    volumes:
      - ./nginx_part6.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080