FROM ubuntu:noble-20250127

RUN apt update && \
    apt install -y gcc libfcgi-dev spawn-fcgi nginx

COPY ./server/s21_server.c .

RUN gcc s21_server.c -lfcgi

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

CMD ["bash", "-c", "spawn-fcgi -p 8080 ./a.out & nginx -g 'daemon off;'"]